version: "3.5"

services:
  gobackend:
    container_name: "goserver"
    build:
      context: ./Backend/GoBackend
      dockerfile: dockerfile.godev
    ports:
      - "8081:8080"
    depends_on: 
        - cdnserver
        - database
    volumes:
      - ./Backend/GoBackend:/app/Backend/GoBackend
      - ./Backend/GoBackend/go.mod:/app/Backend/GoBackend/go.mod
    networks:
      backend:
        ipv4_address: "10.1.0.2"
  cdnserver:
    container_name: "cdnserver"
    build:
      context: ./Backend/CDNServer
      dockerfile: dockerfile.cdn
    ports:
      - "8082:8888"
    volumes:
      - ./Backend/CDNServer:/app/Backend/CDNServer
      - ./Backend/CDNServer/go.mod:/app/Backend/CDNServer/go.mod
    networks:
      backend:
        ipv4_address: "10.1.0.3"
  database:
    container_name: "mongodtb"
    image: mongo:3-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: bet_store
    ports:
      - "8083:27017"
      - "8084:28017"
    volumes:
      - ./Backend/Database/log:/var/log/mongodb
      - ./Backend/Database/startup/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./Backend/Database/data:/data/db
      # - ./Backend/Database/startup:/Backend/Database/startup:ro
    networks:
      backend:
        ipv4_address: "10.1.0.4"
  javabackend:
    container_name: "javabackend"
    build:
      context: ./Backend/JavaBackend
      dockerfile: dockerfile.javadev
    ports:
      - "8085:8081"
    depends_on: 
        - cdnserver
        - database
    volumes:
      - ./Backend/JavaBackend:/app
    networks:
      backend:
        ipv4_address: "10.1.0.5"
  nodebackend:
    container_name: "nodebackend"
    build:
      context: ./Backend/NodeJSBackend
      dockerfile: dockerfile.node
    ports:
      - "8086:5000"
    depends_on: 
        - cdnserver
        - database
    environment:
      MONGO_URI: mongodb://root:root@10.1.0.4:27017/
    volumes:
      - ./Backend/NodeJSBackend/config:/app/config
      - ./Backend/NodeJSBackend/controller:/app/controller
      - ./Backend/NodeJSBackend/middleware:/app/middleware
      - ./Backend/NodeJSBackend/models:/app/models
      - ./Backend/NodeJSBackend/routers:/app/routers
      - ./Backend/NodeJSBackend/server.js:/app/server.js
    networks:
      backend:
        ipv4_address: "10.1.0.6"
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "10.1.0.0/27"