#Config Database
[Database]
Stringconnection = "mongodb://10.1.0.4:27017/"
NAME_DATABASE = "bet_store"

#Config secretkey auth 
[Auth]
Secretkey = "TWluaCAoxJBvw6BuLCBLaMO0aSwgVGnhur9uKQ=="
Issuer = "localhost"

#Config tel auth server
[TelAuthServer]
AUTH_KEY = "QUM4Y2NiYmE4ZmM5YjliMDVlYWQ4YWM4MzFmNmVkNTk0NToxYjhiZmY0Mjg4ZjdhNjA0ZWI1Zjk3OWI3Yjk5ZDJkYg=="
TEL_HOST = "+12053862330"
URL_HOST = "https://api.twilio.com/2010-04-01/Accounts/AC8ccbba8fc9b9b05ead8ac831f6ed5945/Messages.json"